package com.liao.librarydemo.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.liao.librarydemo.bean.dto.FingerDTO;
import com.liao.librarydemo.bean.dto.LoginDTO;

import com.liao.librarydemo.dao.FingerDTODao;
import com.liao.librarydemo.dao.LoginDTODao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig fingerDTODaoConfig;
    private final DaoConfig loginDTODaoConfig;

    private final FingerDTODao fingerDTODao;
    private final LoginDTODao loginDTODao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        fingerDTODaoConfig = daoConfigMap.get(FingerDTODao.class).clone();
        fingerDTODaoConfig.initIdentityScope(type);

        loginDTODaoConfig = daoConfigMap.get(LoginDTODao.class).clone();
        loginDTODaoConfig.initIdentityScope(type);

        fingerDTODao = new FingerDTODao(fingerDTODaoConfig, this);
        loginDTODao = new LoginDTODao(loginDTODaoConfig, this);

        registerDao(FingerDTO.class, fingerDTODao);
        registerDao(LoginDTO.class, loginDTODao);
    }
    
    public void clear() {
        fingerDTODaoConfig.clearIdentityScope();
        loginDTODaoConfig.clearIdentityScope();
    }

    public FingerDTODao getFingerDTODao() {
        return fingerDTODao;
    }

    public LoginDTODao getLoginDTODao() {
        return loginDTODao;
    }

}
